# Generated by Django 3.2 on 2023-01-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ball_softness',
            field=models.IntegerField(blank=True, choices=[(0, 'Soft'), (1, 'Hard')], default=0, null=True),
        ),
    ]
