# Generated by Django 3.2 on 2023-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_ball_softness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='has_loft',
            new_name='driver_loft',
        ),
        migrations.AddField(
            model_name='product',
            name='wedge_loft',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
