# Generated by Django 3.2 on 2023-02-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_dexterity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dexterity',
        ),
    ]
